spring:
  datasource:
    url: "jdbc:postgresql://192.168.0.9:5432/sourcedb?ApplicationName=TestLiquibase"
    username: "postgres"
    password: "postgres"
  liquibase:
    rollback-file: rollback.sql
    tag: "tag-1"
